logging:
  file:
    name: logs/sathishstravaproducer.log
  level:
    sql: INFO
    web: INFO
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://20.121.147.50:8070/eureka/
    registerWithEureka: true
server:
  port: 8065
spring:
  application:
    name: sathishstrava-data-producer
