
spring:
    threads:
        virtual:
            enabled: true
    datasource:
        url: jdbc:postgresql://localhost:5432/skminfotech
        driverClassName: org.postgresql.Driver
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

        flyway:
            locations: classpath:/db/migration/{vendor}
            validate-on-migrate: true
    flyway:
        baseline-on-migrate: true
        enabled: true
        clean-on-validation-error: true
        clean-disabled: false
    rabbitmq:
        host: "localhost"
        port: 5672
        username: "guest"
        password: "guest"
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        show-sql: true
    sql:
        init:
            mode: always
eureka:
    instance:
        preferIpAddress: true
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://sathish:${configserverPassword}@localhost:8888/eureka/
info:
    app:
        name: "trackgarmin"
        version: "1.0.0"
decorator:
    datasource:
        datasource-proxy:
            json-format: true
            format-sql: true

        flexy-pool:
            threshold:
                connection:
                    acquire: -1
                    lease: 0
