
spring:
    threads:
        virtual:
            enabled: true
    datasource:
        url: jdbc:postgresql://testsathisprj1postgres.postgres.database.azure.com:5432/postgres
        driverClassName: org.postgresql.Driver
        username: psqladmin
        password: pas$word1234

        flyway:
            locations: classpath:/db/migration/{vendor}
            validate-on-migrate: true
    flyway:
        baseline-on-migrate: true
        enabled: true
        clean-on-validation-error: true
        clean-disabled: false
    rabbitmq:
        host: "localhost"
        port: 5672
        username: "guest"
        password: "guest"
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                default_schema: postgres
                jdbc:
                    time_zone: UTC
    sql:
        init:
            mode: always
info:
    app:
        name: "trackgarmin"
        version: "1.0.0"
decorator:
    datasource:
        datasource-proxy:
            json-format: true
            format-sql: true

        flexy-pool:
            threshold:
                connection:
                    acquire: -1
                    lease: 0
