management:
    endpoint:
        health:
            show-details: always
        shutdown:
            enabled: true
        info:
            env:
                enabled: true
    endpoints:
        web:
            exposure:
                include: "*"
server:
    shutdown: graceful
spring:
    application:
        name: trackgarmin
    main:
        allow-bean-definition-overriding: true
    mvc:
        problemdetails:
            enabled: true

