spring:
    threads:
        virtual:
            enabled: true
    datasource:
        url: ${garmindb}
        driverClassName: org.postgresql.Driver
        username: ${darmindb_user}
        password: ${darmindb_password}
        schema: runs_schema
    rabbitmq:
        host: "localhost"
        port: 5672
        username: "guest"
        password: "guest"
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    time_zone: UTC
info:
    app:
        name: "trackgarmin"
        version: "1.0.0"
decorator:
    datasource:
        datasource-proxy:
            json-format: true
            format-sql: true
        flexy-pool:
            threshold:
                connection:
                    acquire: -1
                    lease: 0
