logging:
    file:
        name: logs/trackstrava.log
    level:
        sql: INFO
        web: INFO
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"
server:
    port: 8080
    shutdown: graceful
spring:
    application:
        name: trackstrava
    data:
        jpa:
            repositories:
                bootstrap-mode: deferred
    datasource:
        hikari:
            auto-commit: false
    jmx:
        enabled: false
    jpa:
        hibernate:
            ddl-auto: validate
        open-in-view: false
        properties:
            hibernate:
                connection:
                    provider_disables_autocommit: true
                generate_statistics: false
                id:
                    new_generator_mappings: true
                    optimizer:
                        pooled:
                            preferred: pooled-lo
                jdbc:
                    batch_size: 25
                    lob:
                        non_contextual_creation: true
                    time_zone: UTC
                order_inserts: true
                order_updates: true
                query:
                    fail_on_pagination_over_collection_fetch: true
                    in_clause_parameter_padding: true
        show-sql: true
    main:
        allow-bean-definition-overriding: true
    mvc:
        problemdetails:
            enabled: true
