spring:
    rabbitmq:
        host: "localhost"
        port: 5672
        username: "guest"
        password: "guest"
    datasource:
        url: ${garmindb}
        driverClassName: org.postgresql.Driver
        username: ${darmindb_user}
        password: ${darmindb_password}
        schema: runs_schema
        initialization-mode: always
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        open-in-view: false
    sql:
        init:
            mode: always
info:
    app:
        name: "trackstrava"
        version: "1.0.0"
server:
    port: 9032
    shutdown: graceful
decorator:
    datasource:
        datasource-proxy:
            json-format: true
            format-sql: true
        flexy-pool:
            threshold:
                connection:
                    acquire: -1
                    lease: 0
