logging:
    file:
        name: logs/trackstrava.log
    level:
        sql: INFO
        web: INFO
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"
spring:
    application:
        name: trackstrava
    main:
        allow-bean-definition-overriding: true
    mvc:
        problemdetails:
            enabled: true
