team:
  value: GARMIN
  backup: STRAVA
spring:
  datasource:
    url: jdbc:postgresql://testsathisprj1postgres.postgres.database.azure.com:5432/garmin
    driverClassName: org.postgresql.Driver
    username: psqladmin
    password: psqladminpas$

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  threads:
    virtual:
      enabled: true
  sql:
    init:
      mode: always
health:
  config:
    enabled: false
scheduling:
  cron: "0/30 * * * * *"
location:
  fileName: "/activities.csv"
  url: "https://raw.githubusercontent.com/sathishjayapal/jubilant-memory/refs/heads/main/garmindatainitializer/activities1.csv"
