# Golden copy for the client to communicate with Configserver ver #3
# this property file setting will read app name "Accounts", profile "local" and use the retry logic
spring:
  application:
    name: "garmindatainitializer"

