spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    driverClassName: org.postgresql.Driver
    username: appuser
    password: secret

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  threads:
    virtual:
      enabled: true
  sql:
    init:
      mode: always
health:
  config:
    enabled: false
