# Cron expression to schedule tasks every 5 seconds starting at midnight every day
team:
  value: GARMIN
  backup: STRAVA
spring:
  datasource:
    url: ${garmindb}
    driverClassName: org.postgresql.Driver
    username: ${darmindb_user}
    password: ${darmindb_password}
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
health:
  config:
    enabled: true
scheduling:
  cron: "0/30 * * * * *"
location:
  fileName: "/activities.csv"
  url: "https://raw.githubusercontent.com/sathishjayapal/jubilant-memory/refs/heads/main/garmindatainitializer/activities2.csv"
