team:
  value: GARMIN
  backup: STRAVA
spring:
  datasource:
    url: ${garmindb}
    driverClassName: org.postgresql.Driver
    username: ${darmindb_user}
    password: ${darmindb_password}
    open-in-view: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  threads:
    virtual:
      enabled: true
health:
  config:
    enabled: false
scheduling:
  cron: "0/30 * * * * *"
location:
  fileName: "/activities.csv"
  url: "https://raw.githubusercontent.com/sathishjayapal/jubilant-memory/refs/heads/main/garmindatainitializer/activities1.csv"
