# Cron expression to schedule tasks every 5 seconds starting at midnight every day
team:
  value: GARMIN
  backup: STRAVA
spring:
  datasource:
    url: ${garmindb}
    driverClassName: org.postgresql.Driver
    username: ${darmindb_user}
    password: ${darmindb_password}
    schema: runs_schema
    initialization-mode: auto
  jpa:
    schema:
      - runs_schema
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
health:
  config:
    enabled: true
scheduling:
  cron: "0/30 * * * * *"
location:
  fileName: "/activities.csv"
  url:
