# Cron expression to schedule tasks every 5 seconds starting at midnight every day
team:
  value: GARMIN
  backup: STRAVA
spring:
  datasource:
    open-in-view: false
    url: ${garmindb}
    driverClassName: org.postgresql.Driver
    username: ${darmindb_user}
    password: ${darmindb_password}

  jpa:
    hibernate:
    show-sql: true
health:
  config:
    enabled: true
scheduling:
  cron: "0/30 * * * * *"
location:
  fileName: "/activities.csv"
  url:
